#include "generated_kb.h"

namespace cerebras_v3
{
namespace generated_kb
{

const Faq_entry faq_entries[] =
{
  { "recall_service", "recall, manufacturer recall, open recall, recall notice", "The service team can help review recall concerns and confirm next steps when they call back." },
  { "warranty_service", "warranty, manufacturer warranty, warranty coverage", "The service team can review warranty questions and confirm what applies when they call back." },
  { "ev_battery_service", "EV battery, high-voltage battery, electric car battery warning", "The service team can review EV battery concerns and confirm next steps when they call back." },
  { "service_hours", "service hours, when service opens or closes, service department schedule", "Service hours are 9 AM to 5 PM." },
  { "parts_availability", "whether a part can be checked or is available", "The parts team can check availability and confirm options when they call back." },
  { "parts_order_status", "already ordered part status, ordered part arrival, parts order update", "The parts team can review order status and follow up with the latest update." },
  { "sales_inventory", "in stock, on the lot, available vehicles, current inventory", "The sales team can confirm current inventory and follow up with available options." },
  { "financing", "financing, lease rates, monthly payments, credit, approval", "The sales team can review financing questions and follow up with available options." },
  { "trade_in", "trade-in, appraisal, value of current vehicle", "The sales team can review trade-in details and follow up with next steps." },
  { "service-shuttle-service", "Shuttle Service; Local shuttle service for customers during service appointments; shuttle, ride, transport, pickup, dropoff", "Shuttle Service may be available. Local shuttle service for customers during service appointments. Conditions: Available for active service customers. Limits: Limited to 15 mile radius and driver availability. Notes: Not guaranteed during peak hours. The service team can confirm details when they call back." },
  { "service-loaner-vehicle", "Loaner Vehicle; Temporary vehicle provided during longer repairs; loaner, car, rental, replacement vehicle", "Loaner Vehicle may be available. Temporary vehicle provided during longer repairs. Conditions: Requires advisor approval and qualifying repair. Limits: Limited inventory. Notes: Insurance and license required. The service team can confirm details when they call back." },
  { "service-after-hours-drop-off", "After Hours Drop-Off; Customers can drop off vehicles outside business hours; after hours, drop off, night, late, key box", "After Hours Drop-Off is available. Customers can drop off vehicles outside business hours. Conditions: None. Limits: Key drop box only. Notes: Envelope must be filled out." },
  { "service-after-hours-pickup", "After Hours Pickup; Vehicle pickup available after hours; after hours, pickup, late, vehicle pickup", "After Hours Pickup may be available. Vehicle pickup available after hours. Conditions: Must be pre-arranged with advisor. Limits: Access instructions required. Notes: Payment must be completed beforehand. The service team can confirm details when they call back." },
  { "service-free-wi-fi", "Free Wi-Fi; Wi-Fi available in customer waiting area; wifi, internet, waiting room", "Free Wi-Fi is available. Wi-Fi available in customer waiting area. Conditions: None. Limits: None. Notes: Network details provided on-site." },
  { "service-customer-lounge", "Customer Lounge; Indoor waiting area with seating and workspace; lounge, waiting area, seating", "Customer Lounge is available. Indoor waiting area with seating and workspace. Conditions: None. Limits: Capacity may be limited. Notes: Shared space." },
  { "service-coffee-and-refreshments", "Coffee and Refreshments; Complimentary coffee and beverages available; coffee, drinks, refreshments", "Coffee and Refreshments is available. Complimentary coffee and beverages available. Conditions: None. Limits: While supplies last. Notes: Self-serve." },
  { "service-kids-play-area", "Kids Play Area; Designated play space for children; kids area, children, play", "Kids Play Area may be available. Designated play space for children. Conditions: Available during business hours. Limits: May be closed for cleaning or safety. Notes: Supervision required. The service team can confirm details when they call back." },
  { "service-workstations", "Workstations; Work desks available for customers while waiting; workspace, desk, work area", "Workstations is available. Work desks available for customers while waiting. Conditions: None. Limits: Limited seating. Notes: First come first serve." },
  { "service-digital-vehicle-inspection", "Digital Vehicle Inspection; Technicians provide digital inspection reports with photos; inspection, digital report, photos", "Digital Vehicle Inspection is available. Technicians provide digital inspection reports with photos. Conditions: Included with most services. Limits: None. Notes: Sent via text or email." },
  { "service-text-status-updates", "Text Status Updates; Customers receive service updates via text message; text updates, status updates, notifications", "Text Status Updates is available. Customers receive service updates via text message. Conditions: Requires valid phone number. Limits: None. Notes: Opt-in required." },
  { "service-online-payment", "Online Payment; Customers can pay invoices online; online payment, pay bill, invoice", "Online Payment is available. Customers can pay invoices online. Conditions: Available after service completion. Limits: None. Notes: Secure payment portal." },
  { "service-express-service", "Express Service; Quick maintenance services without long wait times; express service, quick oil change, fast service", "Express Service may be available. Quick maintenance services without long wait times. Conditions: Applies to basic services only. Limits: First come first serve. Notes: May have limited hours. The service team can confirm details when they call back." },
  { "service-tire-storage", "Tire Storage; Seasonal tire storage for customers; tire storage, seasonal tires, storage", "Tire Storage may be available. Seasonal tire storage for customers. Conditions: Available for registered customers. Limits: Storage capacity limits apply. Notes: Additional fees may apply. The service team can confirm details when they call back." },
  { "service-ev-service", "EV Service; Service and maintenance for electric vehicles; electric vehicle, ev, tesla, hybrid", "EV Service is available. Service and maintenance for electric vehicles. Conditions: Applies to supported EV models. Limits: None. Notes: Certified technicians required." },
  { "service-diesel-service", "Diesel Service; Service support for diesel vehicles; diesel, truck service", "Diesel Service is available. Service support for diesel vehicles. Conditions: Applies to supported diesel engines. Limits: None. Notes: Specialized technicians." },
  { "service-fleet-service", "Fleet Service; Maintenance and repair services for fleet vehicles; fleet, commercial vehicles, business service", "Fleet Service may be available. Maintenance and repair services for fleet vehicles. Conditions: Requires fleet account or agreement. Limits: Priority scheduling may apply. Notes: Contact advisor for setup. The service team can confirm details when they call back." },
  { "service-warranty-repairs", "Warranty Repairs; Repairs covered under manufacturer warranty; warranty, covered repair", "Warranty Repairs may be available. Repairs covered under manufacturer warranty. Conditions: Vehicle must qualify under warranty terms. Limits: None. Notes: Verification required. The service team can confirm details when they call back." },
  { "service-recall-service", "Recall Service; Manufacturer recall repairs performed at no cost; recall, manufacturer recall, free repair", "Recall Service is available. Manufacturer recall repairs performed at no cost. Conditions: Must match active recall. Limits: None. Notes: Handled per manufacturer guidelines." },
  { "service-valet-pickup-and-delivery", "Valet Pickup and Delivery; Vehicle pickup and return service for customers; valet, pickup, delivery, vehicle pickup", "Valet Pickup and Delivery may be available. Vehicle pickup and return service for customers. Conditions: Available within service area. Limits: Distance and scheduling limits apply. Notes: May require additional fee. The service team can confirm details when they call back." },
};
const int faq_entry_count = sizeof(faq_entries) / sizeof(faq_entries[0]);

const Faq_alias faq_aliases[] =
{
  { "recall", "recall_service" },
  { "recall notice", "recall_service" },
  { "open recall", "recall_service" },
  { "manufacturer recall", "recall_service" },
  { "warranty", "warranty_service" },
  { "under warranty", "warranty_service" },
  { "manufacturer warranty", "warranty_service" },
  { "covered under warranty", "warranty_service" },
  { "ev battery", "ev_battery_service" },
  { "electric car battery", "ev_battery_service" },
  { "high-voltage battery", "ev_battery_service" },
  { "high voltage battery", "ev_battery_service" },
  { "ioniq battery", "ev_battery_service" },
  { "electric battery", "ev_battery_service" },
  { "service hours", "service_hours" },
  { "service open", "service_hours" },
  { "service opens", "service_hours" },
  { "service close", "service_hours" },
  { "service closes", "service_hours" },
  { "open on saturday", "service_hours" },
  { "open sundays", "service_hours" },
  { "in stock", "parts_availability" },
  { "available", "parts_availability" },
  { "parts check", "parts_availability" },
  { "do you have", "parts_availability" },
  { "do y'all stock", "parts_availability" },
  { "do you stock", "parts_availability" },
  { "carry", "parts_availability" },
  { "parts order", "parts_order_status" },
  { "ordered part", "parts_order_status" },
  { "part arrived", "parts_order_status" },
  { "special order", "parts_order_status" },
  { "order status", "parts_order_status" },
  { "update on an order", "parts_order_status" },
  { "on the lot", "sales_inventory" },
  { "available vehicles", "sales_inventory" },
  { "current inventory", "sales_inventory" },
  { "in stock", "sales_inventory" },
  { "electric hyundai", "sales_inventory" },
  { "electric hyundais", "sales_inventory" },
  { "ioniq", "sales_inventory" },
  { "tucson hybrid", "sales_inventory" },
  { "lease rate", "financing" },
  { "lease rates", "financing" },
  { "monthly payment", "financing" },
  { "monthly payments", "financing" },
  { "financing", "financing" },
  { "finance", "financing" },
  { "credit", "financing" },
  { "approval", "financing" },
  { "trade-in", "trade_in" },
  { "trade in", "trade_in" },
  { "trade-ins", "trade_in" },
  { "trade ins", "trade_in" },
  { "appraise", "trade_in" },
  { "appraisal", "trade_in" },
  { "current vehicle", "trade_in" },
  { "current car", "trade_in" },
  { "trade is worth", "trade_in" },
  { "dropoff", "service-shuttle-service" },
  { "pickup", "service-shuttle-service" },
  { "ride", "service-shuttle-service" },
  { "shuttle", "service-shuttle-service" },
  { "shuttle service", "service-shuttle-service" },
  { "transport", "service-shuttle-service" },
  { "car", "service-loaner-vehicle" },
  { "loaner", "service-loaner-vehicle" },
  { "loaner vehicle", "service-loaner-vehicle" },
  { "rental", "service-loaner-vehicle" },
  { "replacement vehicle", "service-loaner-vehicle" },
  { "after hours", "service-after-hours-drop-off" },
  { "after hours drop-off", "service-after-hours-drop-off" },
  { "drop off", "service-after-hours-drop-off" },
  { "key box", "service-after-hours-drop-off" },
  { "late", "service-after-hours-drop-off" },
  { "night", "service-after-hours-drop-off" },
  { "after hours", "service-after-hours-pickup" },
  { "after hours pickup", "service-after-hours-pickup" },
  { "late", "service-after-hours-pickup" },
  { "pickup", "service-after-hours-pickup" },
  { "vehicle pickup", "service-after-hours-pickup" },
  { "free wi-fi", "service-free-wi-fi" },
  { "internet", "service-free-wi-fi" },
  { "waiting room", "service-free-wi-fi" },
  { "wifi", "service-free-wi-fi" },
  { "customer lounge", "service-customer-lounge" },
  { "lounge", "service-customer-lounge" },
  { "seating", "service-customer-lounge" },
  { "waiting area", "service-customer-lounge" },
  { "coffee", "service-coffee-and-refreshments" },
  { "coffee and refreshments", "service-coffee-and-refreshments" },
  { "drinks", "service-coffee-and-refreshments" },
  { "refreshments", "service-coffee-and-refreshments" },
  { "children", "service-kids-play-area" },
  { "kids area", "service-kids-play-area" },
  { "kids play area", "service-kids-play-area" },
  { "play", "service-kids-play-area" },
  { "desk", "service-workstations" },
  { "work area", "service-workstations" },
  { "workspace", "service-workstations" },
  { "workstations", "service-workstations" },
  { "digital report", "service-digital-vehicle-inspection" },
  { "digital vehicle inspection", "service-digital-vehicle-inspection" },
  { "inspection", "service-digital-vehicle-inspection" },
  { "photos", "service-digital-vehicle-inspection" },
  { "notifications", "service-text-status-updates" },
  { "status updates", "service-text-status-updates" },
  { "text status updates", "service-text-status-updates" },
  { "text updates", "service-text-status-updates" },
  { "invoice", "service-online-payment" },
  { "online payment", "service-online-payment" },
  { "pay bill", "service-online-payment" },
  { "express service", "service-express-service" },
  { "fast service", "service-express-service" },
  { "quick oil change", "service-express-service" },
  { "seasonal tires", "service-tire-storage" },
  { "storage", "service-tire-storage" },
  { "tire storage", "service-tire-storage" },
  { "electric vehicle", "service-ev-service" },
  { "ev", "service-ev-service" },
  { "ev service", "service-ev-service" },
  { "hybrid", "service-ev-service" },
  { "tesla", "service-ev-service" },
  { "diesel", "service-diesel-service" },
  { "diesel service", "service-diesel-service" },
  { "truck service", "service-diesel-service" },
  { "business service", "service-fleet-service" },
  { "commercial vehicles", "service-fleet-service" },
  { "fleet", "service-fleet-service" },
  { "fleet service", "service-fleet-service" },
  { "covered repair", "service-warranty-repairs" },
  { "warranty", "service-warranty-repairs" },
  { "warranty repairs", "service-warranty-repairs" },
  { "free repair", "service-recall-service" },
  { "manufacturer recall", "service-recall-service" },
  { "recall", "service-recall-service" },
  { "recall service", "service-recall-service" },
  { "delivery", "service-valet-pickup-and-delivery" },
  { "pickup", "service-valet-pickup-and-delivery" },
  { "valet", "service-valet-pickup-and-delivery" },
  { "valet pickup and delivery", "service-valet-pickup-and-delivery" },
  { "vehicle pickup", "service-valet-pickup-and-delivery" },
};
const int faq_alias_count = sizeof(faq_aliases) / sizeof(faq_aliases[0]);

const char* affirmation_yes_phrases[] =
{
  "yes",
  "correct",
  "yup",
  "yep",
  "yeah",
  "right",
  "that's right",
  "that is right",
  "all correct",
  "that is mine",
  "that's mine",
  "yep that is mine",
  "yup that is mine",
  "looks right",
  "sounds right",
  "correct number",
  "sounds good",
  "that works",
  "all good",
  "perfect",
};
const int affirmation_yes_count = sizeof(affirmation_yes_phrases) / sizeof(affirmation_yes_phrases[0]);

const char* affirmation_no_phrases[] =
{
  "no",
  "nope",
  "not right",
  "not correct",
  "incorrect",
  "wrong",
  "that's wrong",
  "that is wrong",
  "wrong number",
  "not mine",
};
const int affirmation_no_count = sizeof(affirmation_no_phrases) / sizeof(affirmation_no_phrases[0]);

const char* affirmation_unclear_phrases[] =
{
  "maybe",
  "not sure",
  "can you repeat that",
  "say that again",
};
const int affirmation_unclear_count = sizeof(affirmation_unclear_phrases) / sizeof(affirmation_unclear_phrases[0]);

const char* vehicle_models[] =
{
  "1",
  "1 Series",
  "124 Spider",
  "1500 Classic Crew Cab",
  "1500 Classic Quad Cab",
  "1500 Classic Regular Cab",
  "1500 Club Coupe",
  "1500 Crew Cab",
  "1500 Extended Cab",
  "1500 Quad Cab",
  "1500 Ramcharger",
  "1500 Regular Cab",
  "1500 REV",
  "164",
  "2",
  "2 Series",
  "200",
  "200SX",
  "240SX",
  "2500 Club Coupe",
  "2500 Crew Cab",
  "2500 Extended Cab",
  "2500 HD Club Coupe",
  "2500 HD Extended Cab",
  "2500 HD Regular Cab",
  "2500 Mega Cab",
  "2500 Regular Cab",
  "296 GTB",
  "3",
  "3 Series",
  "300",
  "3000GT",
  "300M",
  "300ZX",
  "3500 Club Coupe",
  "3500 Crew Cab",
  "3500 Extended Cab",
  "3500 HD Extended Cab",
  "3500 HD Regular Cab",
  "3500 Mega Cab",
  "3500 Regular Cab",
  "350Z",
  "370Z",
  "4",
  "4 Series",
  "400Z",
  "430 Scuderia",
  "458 Italia",
  "458 Speciale",
  "458 Spider",
  "488 GTB",
  "488 Pista",
  "488 Spider",
  "4C",
  "4C Spider",
  "4Runner",
  "5",
  "5 Series",
  "500",
  "500 Abarth",
  "500c",
  "500c Abarth",
  "500e",
  "500L",
  "500X",
  "57",
  "570GT",
  "570S",
  "599 GTB Fiorano",
  "599 GTO",
  "6 Series",
  "600LT",
  "612 Scaglietti",
  "62",
  "626",
  "650S",
  "675LT",
  "7 Series",
  "718 Boxster",
  "718 Cayman",
  "718 Spyder",
  "720S",
  "8 Series",
  "812 Competizione",
  "812 Competizione A",
  "812 GTS",
  "812 Superfast",
  "850",
  "86",
  "88",
  "9-2X",
  "9-3",
  "9-4X",
  "9-5",
  "9-7X",
  "90",
  "900",
  "9000",
  "911",
  "928",
  "929",
  "940",
  "960",
  "968",
  "98",
  "A-Class",
  "A3",
  "A3 Sportback e-tron",
  "A4",
  "A4 (2005.5)",
  "A4 allroad",
  "A5",
  "A5 Sport",
  "A6",
  "A6 allroad",
  "A7",
  "A8",
  "Acadia",
  "Acadia Limited",
  "Accent",
  "Acclaim",
  "Accord",
  "Accord Crosstour",
  "Accord Hybrid",
  "Achieva",
  "Aerio",
  "Aerostar Cargo",
  "Aerostar Passenger",
  "Air",
  "Alaska",
  "Alero",
  "allroad",
  "Alpina B7",
  "Altima",
  "Amanti",
  "Amigo",
  "Ariya",
  "Armada",
  "Arnage",
  "Arteon",
  "Ascender",
  "Ascent",
  "Aspen",
  "Aspire",
  "Astra",
  "Astro Cargo",
  "Astro Passenger",
  "Atlas",
  "Atlas Cross Sport",
  "ATS",
  "ATS-V",
  "Aura",
  "Aurora",
  "Avalanche",
  "Avalanche 1500",
  "Avalanche 2500",
  "Avalon",
  "Avalon Hybrid",
  "Avenger",
  "Aventador",
  "Aveo",
  "Aviator",
  "Axiom",
  "Azera",
  "Aztek",
  "Azure",
  "Azure T",
  "B-Class",
  "B-Series Cab Plus",
  "B-Series Extended Cab",
  "B-Series Regular Cab",
  "B9 Tribeca",
  "Baja",
  "Beetle",
  "Bentayga",
  "Beretta",
  "Blackwood",
  "Blazer",
  "Blazer EV",
  "Bolt EUV",
  "Bolt EV",
  "Bonneville",
  "Borrego",
  "Boxster",
  "Bravada",
  "Breeze",
  "Bronco",
  "Bronco Sport",
  "Brooklands",
  "BRZ",
  "bZ4X",
  "C-Class",
  "C-HR",
  "C-MAX Energi",
  "C-MAX Hybrid",
  "C/V",
  "C/V Tradesman",
  "C30",
  "C40 Recharge",
  "C70",
  "Cabrio",
  "Cabrio (New)",
  "Cabriolet",
  "Cadenza",
  "Caliber",
  "California",
  "Camaro",
  "Camry",
  "Camry Hybrid",
  "Canyon Crew Cab",
  "Canyon Extended Cab",
  "Canyon Regular Cab",
  "Caprice Classic",
  "Captiva Sport",
  "Caravan Cargo",
  "Caravan Passenger",
  "Carnival",
  "Carrera GT",
  "Cascada",
  "Catera",
  "Cavalier",
  "Cayenne",
  "Cayenne Coupe",
  "Cayman",
  "CC",
  "Celestiq",
  "Celica",
  "Century",
  "Challenger",
  "Charger",
  "Cherokee",
  "Ciera",
  "Cirrus",
  "City Express",
  "Civic",
  "Civic Type R",
  "CL",
  "CL-Class",
  "CLA",
  "CLA-Class",
  "Clarity Electric",
  "Clarity Fuel Cell",
  "Clarity Plug-in Hybrid",
  "Classic",
  "CLE",
  "CLK-Class",
  "CLS",
  "CLS-Class",
  "Club Wagon",
  "Clubman",
  "Cobalt",
  "Colorado Crew Cab",
  "Colorado Extended Cab",
  "Colorado Regular Cab",
  "Commander",
  "Compass",
  "Concorde",
  "Continental",
  "Continental GT",
  "Contour",
  "Convertible",
  "Cooper",
  "Corolla",
  "Corolla Cross",
  "Corolla Cross Hybrid",
  "Corolla Hatchback",
  "Corolla Hybrid",
  "Corolla iM",
  "Corsair",
  "Corsica",
  "Corvette",
  "Cougar",
  "Countryman",
  "Coupe",
  "CR-V",
  "CR-V Hybrid",
  "CR-Z",
  "Crossfire",
  "Crosstour",
  "Crosstrek",
  "Crown",
  "Crown Signia",
  "Crown Victoria",
  "Cruze",
  "Cruze Limited",
  "CT",
  "CT4",
  "CT5",
  "CT6",
  "CT6-V",
  "CTS",
  "CTS-V",
  "cube",
  "Cullinan",
  "Cutlass",
  "Cutlass Ciera",
  "Cutlass Supreme",
  "CX-3",
  "CX-30",
  "CX-5",
  "CX-50",
  "CX-7",
  "CX-70",
  "CX-9",
  "CX-90",
  "CX-90 PHEV",
  "Cybertruck",
  "Dakota Club Cab",
  "Dakota Crew Cab",
  "Dakota Extended Cab",
  "Dakota Quad Cab",
  "Dakota Regular Cab",
  "Dart",
  "Dawn",
  "DB11",
  "DB9",
  "DB9 GT",
  "DBS",
  "DBS Superleggera",
  "DBX",
  "Defender 110",
  "Defender 130",
  "Defender 90",
  "del Sol",
  "DeVille",
  "Diamante",
  "Discovery",
  "Discovery Series II",
  "Discovery Sport",
  "DTS",
  "Durango",
  "E-Class",
  "e-Golf",
  "E-PACE",
  "E-Transit 350 Cargo Van",
  "e-tron",
  "e-tron GT",
  "e-tron S",
  "e-tron S Sportback",
  "e-tron Sportback",
  "E150 Cargo",
  "E150 Passenger",
  "E150 Super Duty Cargo",
  "E150 Super Duty Passenger",
  "E250 Cargo",
  "E250 Super Duty Cargo",
  "E350 Super Duty Cargo",
  "E350 Super Duty Passenger",
  "Echo",
  "Eclipse",
  "Eclipse Cross",
  "Econoline E150 Cargo",
  "Econoline E150 Passenger",
  "Econoline E250 Cargo",
  "Econoline E350 Cargo",
  "Econoline E350 Super Duty Cargo",
  "Econoline E350 Super Duty Passenger",
  "EcoSport",
  "Edge",
  "Elantra",
  "Elantra GT",
  "Elantra Hybrid",
  "Elantra N",
  "Eldorado",
  "Electrified G80",
  "Electrified GV70",
  "Element",
  "Elise",
  "ELR",
  "Enclave",
  "Encore",
  "Encore GX",
  "Endeavor",
  "Entourage",
  "Envision",
  "Envista",
  "Envoy",
  "Envoy XL",
  "Envoy XUV",
  "Eos",
  "Equator Crew Cab",
  "Equator Extended Cab",
  "Equinox",
  "Equinox EV",
  "Equus",
  "ES",
  "Escalade",
  "Escalade ESV",
  "Escalade EXT",
  "Escalade IQ",
  "Escape",
  "Escape Plug-in Hybrid",
  "Escort",
  "Esperante",
  "eSprinter",
  "Esteem",
  "Eurovan",
  "EV6",
  "EV9",
  "Evora",
  "Evora 400",
  "Evora GT",
  "EX",
  "EX30",
  "EX90",
  "Excursion",
  "Exige",
  "Exige S",
  "Expedition",
  "Expedition EL",
  "Expedition MAX",
  "Explorer",
  "Explorer Sport",
  "Explorer Sport Trac",
  "Expo",
  "Express 1500 Cargo",
  "Express 1500 Passenger",
  "Express 2500 Cargo",
  "Express 2500 Passenger",
  "Express 3500 Cargo",
  "Express 3500 Passenger",
  "F-PACE",
  "F-TYPE",
  "F12berlinetta",
  "F150 (Heritage) Regular Cab",
  "F150 (Heritage) Super Cab",
  "F150 Lightning",
  "F150 Regular Cab",
  "F150 Super Cab",
  "F150 SuperCrew Cab",
  "F250 Crew Cab",
  "F250 Regular Cab",
  "F250 Super Cab",
  "F250 Super Duty Crew Cab",
  "F250 Super Duty Regular Cab",
  "F250 Super Duty Super Cab",
  "F350 Crew Cab",
  "F350 Regular Cab",
  "F350 Super Cab",
  "F350 Super Duty Crew Cab",
  "F350 Super Duty Regular Cab",
  "F350 Super Duty Super Cab",
  "F430",
  "F450 Super Duty Crew Cab",
  "F450 Super Duty Regular Cab",
  "F8",
  "FF",
  "Fiesta",
  "Firebird",
  "Fit",
  "Five Hundred",
  "FJ Cruiser",
  "Fleetwood",
  "Flex",
  "Flying Spur",
  "Focus",
  "Focus ST",
  "Forenza",
  "Forester",
  "Forte",
  "Forte Koup",
  "Forte5",
  "fortwo",
  "fortwo cabrio",
  "fortwo electric drive",
  "fortwo electric drive cabrio",
  "fortwo EQ cabrio",
  "fortwo EQ coupe",
  "FR-S",
  "Freelander",
  "Freestar Cargo",
  "Freestar Passenger",
  "Freestyle",
  "Frontier Crew Cab",
  "Frontier King Cab",
  "Frontier Regular Cab",
  "Fusion",
  "Fusion Energi",
  "Fusion Plug-in Hybrid",
  "FX",
  "G",
  "G-Class",
  "G-Series 1500",
  "G-Series 2500",
  "G-Series 3500",
  "G-Series G10",
  "G-Series G20",
  "G-Series G30",
  "G3",
  "G5",
  "G6",
  "G6 (2009.5)",
  "G70",
  "G8",
  "G80",
  "G90",
  "Galant",
  "Gallardo",
  "Genesis",
  "Genesis Coupe",
  "Ghibli",
  "Ghost",
  "Giulia",
  "GL-Class",
  "GLA",
  "GLA-Class",
  "Gladiator",
  "GLB",
  "GLC",
  "GLC Coupe",
  "GLE",
  "GLE Coupe",
  "GLI",
  "GLK-Class",
  "GLS",
  "Golf",
  "Golf (New)",
  "Golf Alltrack",
  "Golf GTI",
  "Golf III",
  "Golf R",
  "Golf SportWagen",
  "GR Corolla",
  "GR Supra",
  "GR86",
  "Grand Am",
  "Grand Caravan Cargo",
  "Grand Caravan Passenger",
  "Grand Cherokee",
  "Grand Cherokee 4xe",
  "Grand Cherokee L",
  "Grand Highlander",
  "Grand Highlander Hybrid",
  "Grand Marquis",
  "Grand Prix",
  "Grand Vitara",
  "Grand Voyager",
  "Grand Wagoneer",
  "Grand Wagoneer L",
  "GranSport",
  "GranTurismo",
  "Gravity",
  "Grecale",
  "GS",
  "GT",
  "GT-R",
  "GTC4Lusso",
  "GTI",
  "GTI (New)",
  "GTO",
  "GV60",
  "GV70",
  "GV80",
  "GV80 Coupe",
  "GX",
  "H1",
  "H2",
  "H3",
  "H3T",
  "Hardtop",
  "Hardtop 2 Door",
  "Hardtop 4 Door",
  "HHR",
  "Highlander",
  "Highlander Hybrid",
  "Hombre Regular Cab",
  "Hombre Spacecab",
  "Hornet",
  "HR-V",
  "HS",
  "HUMMER EV Pickup",
  "Hummer EV Pickup",
  "HUMMER EV SUV",
  "Huracan",
  "I",
  "i-280 Extended Cab",
  "i-290 Extended Cab",
  "i-350 Crew Cab",
  "i-370 Crew Cab",
  "i-370 Extended Cab",
  "i-MiEV",
  "I-PACE",
  "i3",
  "i4",
  "i5",
  "i7",
  "i8",
  "iA",
  "ID.4",
  "ID.7",
  "ID.Buzz",
  "ILX",
  "iM",
  "Impala",
  "Impala Limited",
  "Impreza",
  "Insight",
  "Integra",
  "Intrepid",
  "Intrigue",
  "Ion",
  "IONIQ 5",
  "IONIQ 6",
  "IONIQ 7",
  "Ioniq Electric",
  "Ioniq Hybrid",
  "Ioniq Plug-in Hybrid",
  "iQ",
  "IS",
  "IS F",
  "iX",
  "J",
  "Jetta",
  "Jetta (New)",
  "Jetta GLI",
  "Jetta III",
  "Jetta SportWagen",
  "Jimmy",
  "Journey",
  "JUKE",
  "JX",
  "K5",
  "K900",
  "Karma",
  "Kicks",
  "King Cab",
  "Kizashi",
  "Kona",
  "Kona Electric",
  "Kona N",
  "L-Series",
  "LaCrosse",
  "Lancer",
  "Lancer Evolution",
  "Land Cruiser",
  "Lanos",
  "LC",
  "LEAF",
  "LeBaron",
  "Legacy",
  "Leganza",
  "Legend",
  "LeSabre",
  "Levante",
  "LFA",
  "LHS",
  "Liberty",
  "LR2",
  "LR3",
  "LR4",
  "LS",
  "LSS",
  "Lucerne",
  "Lumina",
  "Lumina Cargo",
  "Lumina Passenger",
  "LX",
  "LYRIQ",
  "M",
  "M-Class",
  "M2",
  "M3",
  "M4",
  "M5",
  "M6",
  "M8",
  "Macan",
  "Magnum",
  "Malibu",
  "Malibu (Classic)",
  "Malibu Limited",
  "Marauder",
  "Mariner",
  "Mark LT",
  "Mark VIII",
  "Matrix",
  "Maverick",
  "Maxima",
  "MAZDA2",
  "MAZDA3",
  "MAZDA5",
  "MAZDA6",
  "MC20",
  "MDX",
  "MDX Sport Hybrid",
  "Mercedes-AMG A-Class",
  "Mercedes-AMG C-Class",
  "Mercedes-AMG CLA",
  "Mercedes-AMG CLS",
  "Mercedes-AMG E-Class",
  "Mercedes-AMG EQE",
  "Mercedes-AMG EQE SUV",
  "Mercedes-AMG EQS",
  "Mercedes-AMG G-Class",
  "Mercedes-AMG GLA",
  "Mercedes-AMG GLB",
  "Mercedes-AMG GLC",
  "Mercedes-AMG GLC Coupe",
  "Mercedes-AMG GLE",
  "Mercedes-AMG GLE Coupe",
  "Mercedes-AMG GLS",
  "Mercedes-AMG GT",
  "Mercedes-AMG S-Class",
  "Mercedes-AMG SL",
  "Mercedes-AMG SLC",
  "Mercedes-AMG SLK",
  "Mercedes-EQ EQB",
  "Mercedes-EQ EQE",
  "Mercedes-EQ EQE SUV",
  "Mercedes-EQ EQS",
  "Mercedes-EQ EQS SUV",
  "Mercedes-Maybach EQS SUV",
  "Mercedes-Maybach GLS",
  "Mercedes-Maybach S 600",
  "Mercedes-Maybach S-Class",
  "Metris Cargo",
  "Metris Passenger",
  "Metris WORKER Cargo",
  "Metris WORKER Passenger",
  "Metro",
  "Mighty Max Regular Cab",
  "Milan",
  "Millenia",
  "Mirage",
  "Mirage G4",
  "Mirai",
  "MKC",
  "MKS",
  "MKT",
  "MKX",
  "MKZ",
  "Model 3",
  "Model S",
  "Model X",
  "Model Y",
  "Montana",
  "Montana SV6",
  "Monte Carlo",
  "Montego",
  "Monterey",
  "Montero",
  "Montero Sport",
  "Mountaineer",
  "MP4-12C",
  "MPV",
  "MR2",
  "Mulsanne",
  "Murano",
  "Murcielago",
  "Murcielago LP640",
  "Mustang",
  "Mustang MACH-E",
  "MX-3",
  "MX-30",
  "MX-5 Miata",
  "MX-5 Miata RF",
  "MX-6",
  "Mystique",
  "Nautilus",
  "Navigator",
  "Navigator L",
  "Neon",
  "New Beetle",
  "New Yorker",
  "NEXO",
  "Niro",
  "Niro EV",
  "Niro Plug-in Hybrid",
  "Nitro",
  "NSX",
  "Nubira",
  "NV1500 Cargo",
  "NV200",
  "NV200 Taxi",
  "NV2500 HD Cargo",
  "NV3500 HD Cargo",
  "NV3500 HD Passenger",
  "NX",
  "Oasis",
  "Ocean",
  "Odyssey",
  "Optima",
  "Optima (2006.5)",
  "Optima Hybrid",
  "Optima Plug-in Hybrid",
  "OPTIQ",
  "Outback",
  "Outlander",
  "Outlander PHEV",
  "Outlander Sport",
  "Outlook",
  "Paceman",
  "Pacifica",
  "Pacifica Hybrid",
  "Palisade",
  "Panamera",
  "Park Avenue",
  "Paseo",
  "Passat",
  "Passat (New)",
  "Passport",
  "Pathfinder",
  "Pathfinder Armada",
  "Patriot",
  "Pear",
  "Phaeton",
  "Phantom",
  "Pilot",
  "Portofino",
  "Prelude",
  "Previa",
  "Prius",
  "Prius c",
  "Prius Plug-in Hybrid",
  "Prius Prime",
  "Prius v",
  "Prizm",
  "Probe",
  "Prologue",
  "ProMaster 1500 Cargo",
  "ProMaster 2500 Cargo",
  "ProMaster 3500 Cargo",
  "ProMaster Cargo Van",
  "ProMaster City",
  "ProMaster Window Van",
  "Protege",
  "Protege5",
  "Prowler",
  "PT Cruiser",
  "Q",
  "Q3",
  "Q4 e-tron",
  "Q4 Sportback e-tron",
  "Q40",
  "Q5",
  "Q5 Sportback",
  "Q50",
  "Q6 e-tron",
  "Q60",
  "Q7",
  "Q70",
  "Q8",
  "Q8 e-tron",
  "Q8 Sportback e-tron",
  "Quattroporte",
  "Quest",
  "QX",
  "QX30",
  "QX50",
  "QX55",
  "QX60",
  "QX70",
  "QX80",
  "R-Class",
  "R1S",
  "R1T",
  "R32",
  "R8",
  "Rabbit",
  "Raider Double Cab",
  "Raider Extended Cab",
  "Rainier",
  "Rally Wagon G2500",
  "Rally Wagon G3500",
  "Ram 1500 Club Cab",
  "Ram 1500 Crew Cab",
  "Ram 1500 Mega Cab",
  "Ram 1500 Quad Cab",
  "Ram 1500 Regular Cab",
  "Ram 2500 Club Cab",
  "Ram 2500 Crew Cab",
  "Ram 2500 Mega Cab",
  "Ram 2500 Quad Cab",
  "Ram 2500 Regular Cab",
  "Ram 3500 Club Cab",
  "Ram 3500 Crew Cab",
  "Ram 3500 Mega Cab",
  "Ram 3500 Quad Cab",
  "Ram 3500 Regular Cab",
  "Ram Van 1500",
  "Ram Van 2500",
  "Ram Van 3500",
  "Ram Wagon 1500",
  "Ram Wagon 2500",
  "Ram Wagon 3500",
  "Range Rover",
  "Range Rover Evoque",
  "Range Rover Sport",
  "Range Rover Velar",
  "Ranger Regular Cab",
  "Ranger Super Cab",
  "Ranger SuperCab",
  "Ranger SuperCrew",
  "Rapide",
  "Rapide S",
  "RAV4",
  "RAV4 Hybrid",
  "RAV4 Prime",
  "RC",
  "RDX",
  "Recon",
  "Regal",
  "Regal Sportback",
  "Regal TourX",
  "Regency",
  "Regular Cab",
  "Relay",
  "Rendezvous",
  "Renegade",
  "Reno",
  "Ridgeline",
  "Rio",
  "Riviera",
  "RL",
  "RLX",
  "RLX Sport Hybrid",
  "Roadmaster",
  "Roadster",
  "Rodeo",
  "Rodeo Sport",
  "Rogue",
  "Rogue Select",
  "Rogue Sport",
  "Roma",
  "Rondo",
  "Ronin",
  "Routan",
  "RS 3",
  "RS 4",
  "RS 5",
  "RS 6",
  "RS 7",
  "RS e-tron GT",
  "RS Q8",
  "RSX",
  "RX",
  "RX-7",
  "RX-8",
  "RZ",
  "S-Class",
  "S-Series",
  "S-Type",
  "S10 Crew Cab",
  "S10 Extended Cab",
  "S10 Regular Cab",
  "S2000",
  "S3",
  "S4",
  "S4 (2005.5)",
  "S40",
  "S40 (New)",
  "S5",
  "S6",
  "S60",
  "S7",
  "S70",
  "S8",
  "S80",
  "S90",
  "Sable",
  "Safari Cargo",
  "Safari Passenger",
  "Samurai",
  "Santa Cruz",
  "Santa Fe",
  "Santa Fe Hybrid",
  "Santa Fe Plug-in Hybrid",
  "Santa Fe Sport",
  "Santa Fe XL",
  "Savana 1500 Cargo",
  "Savana 1500 Passenger",
  "Savana 2500 Cargo",
  "Savana 2500 Passenger",
  "Savana 3500 Cargo",
  "Savana 3500 Passenger",
  "SC",
  "Scoupe",
  "Sebring",
  "Sedona",
  "Seltos",
  "Sentra",
  "Sephia",
  "Sequoia",
  "Seville",
  "SF90",
  "Sidekick",
  "Sienna",
  "Sierra (Classic) 1500 Crew Cab",
  "Sierra (Classic) 1500 Extended Cab",
  "Sierra (Classic) 1500 HD Crew Cab",
  "Sierra (Classic) 1500 Regular Cab",
  "Sierra (Classic) 2500 Crew Cab",
  "Sierra (Classic) 2500 HD Crew Cab",
  "Sierra (Classic) 2500 HD Extended Cab",
  "Sierra (Classic) 2500 HD Regular Cab",
  "Sierra (Classic) 3500 Crew Cab",
  "Sierra (Classic) 3500 Extended Cab",
  "Sierra (Classic) 3500 Regular Cab",
  "Sierra 1500 Crew Cab",
  "Sierra 1500 Double Cab",
  "Sierra 1500 Extended Cab",
  "Sierra 1500 HD Crew Cab",
  "Sierra 1500 Limited Crew Cab",
  "Sierra 1500 Limited Double Cab",
  "Sierra 1500 Limited Regular Cab",
  "Sierra 1500 Regular Cab",
  "Sierra 2500 Crew Cab",
  "Sierra 2500 Extended Cab",
  "Sierra 2500 HD Crew Cab",
  "Sierra 2500 HD Double Cab",
  "Sierra 2500 HD Extended Cab",
  "Sierra 2500 HD Regular Cab",
  "Sierra 2500 Regular Cab",
  "Sierra 3500 Crew Cab",
  "Sierra 3500 Extended Cab",
  "Sierra 3500 HD Crew Cab",
  "Sierra 3500 HD Double Cab",
  "Sierra 3500 HD Extended Cab",
  "Sierra 3500 HD Regular Cab",
  "Sierra 3500 Regular Cab",
  "Sierra EV",
  "Silhouette",
  "Silverado (Classic) 1500 Crew Cab",
  "Silverado (Classic) 1500 Extended Cab",
  "Silverado (Classic) 1500 HD Crew Cab",
  "Silverado (Classic) 1500 Regular Cab",
  "Silverado (Classic) 2500 HD Crew Cab",
  "Silverado (Classic) 2500 HD Extended Cab",
  "Silverado (Classic) 2500 HD Regular Cab",
  "Silverado (Classic) 3500 Crew Cab",
  "Silverado (Classic) 3500 Extended Cab",
  "Silverado (Classic) 3500 Regular Cab",
  "Silverado 1500 Crew Cab",
  "Silverado 1500 Double Cab",
  "Silverado 1500 Extended Cab",
  "Silverado 1500 HD Crew Cab",
  "Silverado 1500 LD Double Cab",
  "Silverado 1500 Limited Crew Cab",
  "Silverado 1500 Limited Double Cab",
  "Silverado 1500 Limited Regular Cab",
  "Silverado 1500 Regular Cab",
  "Silverado 2500 Crew Cab",
  "Silverado 2500 Extended Cab",
  "Silverado 2500 HD Crew Cab",
  "Silverado 2500 HD Double Cab",
  "Silverado 2500 HD Extended Cab",
  "Silverado 2500 HD Regular Cab",
  "Silverado 2500 Regular Cab",
  "Silverado 3500 Crew Cab",
  "Silverado 3500 Extended Cab",
  "Silverado 3500 HD Crew Cab",
  "Silverado 3500 HD Double Cab",
  "Silverado 3500 HD Extended Cab",
  "Silverado 3500 HD Regular Cab",
  "Silverado 3500 Regular Cab",
  "Silverado EV",
  "SKY",
  "Skylark",
  "SL",
  "SL-Class",
  "SLC",
  "SLK",
  "SLK-Class",
  "SLR McLaren",
  "SLS-Class",
  "SLX",
  "Solara",
  "Solstice",
  "Solterra",
  "Sonata",
  "Sonata Hybrid",
  "Sonata Plug-in Hybrid",
  "Sonic",
  "Sonoma Club Coupe Cab",
  "Sonoma Crew Cab",
  "Sonoma Extended Cab",
  "Sonoma Regular Cab",
  "Sorento",
  "Sorento Hybrid",
  "Sorento Plug-in Hybrid",
  "Soul",
  "Soul EV",
  "Spark",
  "Spark EV",
  "Spectra",
  "Spirit",
  "Sportage",
  "Sportage Hybrid",
  "Sportage Plug-in Hybrid",
  "Sportvan G20",
  "Sportvan G30",
  "Sprinter 1500 Cargo",
  "Sprinter 1500 Passenger",
  "Sprinter 2500 Cargo",
  "Sprinter 2500 Crew",
  "Sprinter 2500 Passenger",
  "Sprinter 3500 Cargo",
  "Sprinter 3500 Crew",
  "Sprinter 3500 XD Cargo",
  "Sprinter 3500 XD Crew",
  "Sprinter 3500XD Cargo",
  "Sprinter 4500 Cargo",
  "Sprinter 4500 Crew",
  "Sprinter WORKER Cargo",
  "Sprinter WORKER Passenger",
  "SQ5",
  "SQ5 Sportback",
  "SQ7",
  "SQ8",
  "SQ8 e-tron",
  "SQ8 Sportback e-tron",
  "SRX",
  "SS",
  "SSR",
  "Stealth",
  "Stelvio",
  "Stinger",
  "Stratus",
  "STS",
  "Suburban",
  "Suburban 1500",
  "Suburban 2500",
  "Suburban 3500HD",
  "Summit",
  "Sunfire",
  "Supra",
  "SVX",
  "Swift",
  "SX4",
  "T100 Regular Cab",
  "T100 Xtracab",
  "Tacoma Access Cab",
  "Tacoma Double Cab",
  "Tacoma Regular Cab",
  "Tacoma Xtracab",
  "Tacoma XtraCab",
  "Tahoe",
  "Tahoe (New)",
  "Talon",
  "Taos",
  "Taurus",
  "Taurus X",
  "Taycan",
  "Taycan Cross Turismo",
  "Taycan Sport Turismo",
  "tC",
  "Telluride",
  "Tercel",
  "Terrain",
  "Terraza",
  "Thunderbird",
  "Tiburon",
  "Tiguan",
  "Tiguan Limited",
  "Titan Crew Cab",
  "Titan King Cab",
  "TITAN Single Cab",
  "TITAN XD Crew Cab",
  "TITAN XD King Cab",
  "TITAN XD Single Cab",
  "TL",
  "TLX",
  "Tonale",
  "Torrent",
  "Touareg",
  "Touareg 2",
  "Town & Country",
  "Town Car",
  "Tracer",
  "Tracker",
  "Trailblazer",
  "TrailBlazer",
  "Trans Sport",
  "Transit 150 Cargo Van",
  "Transit 150 Crew Van",
  "Transit 150 Passenger Van",
  "Transit 150 Van",
  "Transit 150 Wagon",
  "Transit 250 Cargo Van",
  "Transit 250 Crew Van",
  "Transit 250 Van",
  "Transit 350 Cargo Van",
  "Transit 350 Crew Van",
  "Transit 350 HD Cargo Van",
  "Transit 350 HD Crew Van",
  "Transit 350 HD Van",
  "Transit 350 Passenger Van",
  "Transit 350 Van",
  "Transit 350 Wagon",
  "Transit Connect Cargo",
  "Transit Connect Cargo Van",
  "Transit Connect Passenger",
  "Transit Connect Passenger Wagon",
  "Traverse",
  "Traverse Limited",
  "Trax",
  "Tribeca",
  "Tribute",
  "Trooper",
  "TSX",
  "TT",
  "Tucson",
  "Tucson Fuel Cell",
  "Tucson Hybrid",
  "Tucson Plug-in Hybrid",
  "Tundra Access Cab",
  "Tundra CrewMax",
  "Tundra Double Cab",
  "Tundra Hybrid CrewMax",
  "Tundra Regular Cab",
  "TX",
  "Uplander Cargo",
  "Uplander Passenger",
  "Urus",
  "UX",
  "V40",
  "V50",
  "V60",
  "V70",
  "V90",
  "Vandura G1500",
  "Vandura G2500",
  "Vandura G3500",
  "Vanquish",
  "Vanquish S",
  "Vantage",
  "VehiCROSS",
  "Veloster",
  "Venture Cargo",
  "Venture Passenger",
  "Venue",
  "Venza",
  "Veracruz",
  "Verano",
  "Verona",
  "Versa",
  "Versa Note",
  "VF 6",
  "VF 7",
  "VF 8",
  "VF 9",
  "Vibe",
  "Villager",
  "Viper",
  "Virage",
  "Vision",
  "Vistiq",
  "Vitara",
  "Volt",
  "Voyager",
  "VUE",
  "Wagoneer",
  "Wagoneer L",
  "Windstar Cargo",
  "Windstar Passenger",
  "Wraith",
  "Wrangler",
  "Wrangler 2 Door",
  "Wrangler 4 Door",
  "Wrangler 4xe",
  "Wrangler Unlimited",
  "Wrangler Unlimited 4xe",
  "WRX",
  "X-90",
  "X-Type",
  "X1",
  "X2",
  "X3",
  "X3 M",
  "X4",
  "X4 M",
  "X5",
  "X5 M",
  "X6",
  "X6 M",
  "X7",
  "xA",
  "xB",
  "XC40",
  "XC40 Recharge",
  "XC60",
  "XC70",
  "XC90",
  "xD",
  "XE",
  "XF",
  "XG300",
  "XG350",
  "XJ",
  "XK",
  "XL-7",
  "XL7",
  "XLR",
  "XM",
  "XT4",
  "XT5",
  "XT6",
  "Xterra",
  "Xtra Cab",
  "XTS",
  "XV Crosstrek",
  "Yaris",
  "Yaris Hatchback",
  "Yaris iA",
  "Yukon",
  "Yukon Denali",
  "Yukon XL",
  "Yukon XL 1500",
  "Yukon XL 2500",
  "Z",
  "Z3",
  "Z4",
  "Z4 M",
  "Z8",
  "ZDX",
  "Zephyr",
  "ZX2",
};
const int vehicle_model_count = sizeof(vehicle_models) / sizeof(vehicle_models[0]);

const char* vehicle_aliases[] =
{
  "ionic 5",
  "ioniq five",
  "palisades",
  "santa fe hybrid",
};
const int vehicle_alias_count = sizeof(vehicle_aliases) / sizeof(vehicle_aliases[0]);

const char* interpreter_faq_rules =
  "f must be exactly one of: recall_service, warranty_service, ev_battery_service, service_hours, parts_availability, parts_order_status, sales_inventory, financing, trade_in, service-shuttle-service, service-loaner-vehicle, service-after-hours-drop-off, service-after-hours-pickup, service-free-wi-fi, service-customer-lounge, service-coffee-and-refreshments, service-kids-play-area, service-workstations, service-digital-vehicle-inspection, service-text-status-updates, service-online-payment, service-express-service, service-tire-storage, service-ev-service, service-diesel-service, service-fleet-service, service-warranty-repairs, service-recall-service, service-valet-pickup-and-delivery. FAQ meanings: recall_service=recall, manufacturer recall, open recall, recall notice; warranty_service=warranty, manufacturer warranty, warranty coverage; ev_battery_service=EV battery, high-voltage battery, electric car battery warning; service_hours=service hours, when service opens or closes, service department schedule; parts_availability=whether a part can be checked or is available; parts_order_status=already ordered part status, ordered part arrival, parts order update; sales_inventory=in stock, on the lot, available vehicles, current inventory; financing=financing, lease rates, monthly payments, credit, approval; trade_in=trade-in, appraisal, value of current vehicle; service-shuttle-service=Shuttle Service; Local shuttle service for customers during service appointments; shuttle, ride, transport, pickup, dropoff; service-loaner-vehicle=Loaner Vehicle; Temporary vehicle provided during longer repairs; loaner, car, rental, replacement vehicle; service-after-hours-drop-off=After Hours Drop-Off; Customers can drop off vehicles outside business hours; after hours, drop off, night, late, key box; service-after-hours-pickup=After Hours Pickup; Vehicle pickup available after hours; after hours, pickup, late, vehicle pickup; service-free-wi-fi=Free Wi-Fi; Wi-Fi available in customer waiting area; wifi, internet, waiting room; service-customer-lounge=Customer Lounge; Indoor waiting area with seating and workspace; lounge, waiting area, seating; service-coffee-and-refreshments=Coffee and Refreshments; Complimentary coffee and beverages available; coffee, drinks, refreshments; service-kids-play-area=Kids Play Area; Designated play space for children; kids area, children, play; service-workstations=Workstations; Work desks available for customers while waiting; workspace, desk, work area; service-digital-vehicle-inspection=Digital Vehicle Inspection; Technicians provide digital inspection reports with photos; inspection, digital report, photos; service-text-status-updates=Text Status Updates; Customers receive service updates via text message; text updates, status updates, notifications; service-online-payment=Online Payment; Customers can pay invoices online; online payment, pay bill, invoice; service-express-service=Express Service; Quick maintenance services without long wait times; express service, quick oil change, fast service; service-tire-storage=Tire Storage; Seasonal tire storage for customers; tire storage, seasonal tires, storage; service-ev-service=EV Service; Service and maintenance for electric vehicles; electric vehicle, ev, tesla, hybrid; service-diesel-service=Diesel Service; Service support for diesel vehicles; diesel, truck service; service-fleet-service=Fleet Service; Maintenance and repair services for fleet vehicles; fleet, commercial vehicles, business service; service-warranty-repairs=Warranty Repairs; Repairs covered under manufacturer warranty; warranty, covered repair; service-recall-service=Recall Service; Manufacturer recall repairs performed at no cost; recall, manufacturer recall, free repair; service-valet-pickup-and-delivery=Valet Pickup and Delivery; Vehicle pickup and return service for customers; valet, pickup, delivery, vehicle pickup. Priority: trade_in beats sales_inventory; financing beats sales_inventory; ev_battery_service beats warranty_service; parts_order_status beats parts_availability.";

const char* interpreter_affirmation_rules =
  "a must be exactly one of: none, yes, no, unclear. Use a=yes only when the caller affirms or confirms the assistant's previous yes/no confirmation, like correct, that's right, yep, sounds good, that is mine. Use a=no for wrong, not correct, nope, wrong number, or not mine.";

}
}
